name: ecommerce_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3



flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_small.png"


flutter:

 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
 


